### PR TITLE
Bn edit employee add computer

### PR DESCRIPTION
**Pull request by BryanNilsen**
Ticket #4 Edit Employee
Can edit employee first and last name
Can assign employee to different department
Can assign or remove supervisor status
Can change computer assigned to employee and update computer availability status

### CODE REVIEW

**Comment by ousamasama** [comment]
looks/works great.

👁 ❤️ 🇮🇹 ❗️

**Review by laboyd001 — APPROVED** [review]
edit works outside of known  🐛

**Comment by CurtainUp** [comment]
🐱‍👤
Ok to merge with known bugs: 

Swaps current comp with first unassigned comp selection upon save.
Bonks upon save when no current computer and no available computers.

**Comment by ousamasama** [comment]
⚠️ 🐛 ⚠️

**Pull request merged**
