### PR TITLE
completed issue #7 and required test

### PR DESCRIPTION
**Pull request by ousamasama**
-added department detail pages
-followed team formatting
-added relevant test
-removed employees from all departments page and move to department detail page as specified
-added ".00" to budgets
-issue #12 falls into what was completed as well

### CODE REVIEW

**Review by laboyd001 — APPROVED** [review]
🦆 
9 tests run with 'OK' status
department details visible

**Comment by CurtainUp** [comment]
Need to add filter so department only lists current employees. Currently lists Rick Sanchez for IT even though he is no longer employed.

**Comment by BryanNilsen** [comment]
🐺 🐺

**Comment by CurtainUp** [comment]
🐱‍👤 ran 10 successful tests. data from new migration is appearing and being filtered.

**Review by laboyd001 — APPROVED** [review]
🦆 
departments update with employee count works great

**Pull request merged**
